{
  lib,
  wlib,
  pkgs,
  config,
  ...
}:
let
  tomlFmt = pkgs.formats.toml { };
in
{
  imports = [ wlib.modules.default ];
  options = {
    settings = lib.mkOption {
      inherit (tomlFmt) type;
      default = { };
      description = ''
        Configuration settings for halloy. All available options can be
        found here: <https://halloy.chat/configuration.html>. Note that
        halloy requires at least one `server` to be configured, see example.
      '';
      example = {
        "buffer.channel.topic".enabled = true;
        "servers.liberachat" = {
          nickname = "halloy-user";
          server = "irc.libera.chat";
          channels = [ "#halloy" ];
        };
      };
    };
    themes = lib.mkOption {
      type = lib.types.attrsOf (
        lib.types.oneOf [
          tomlFmt.type
          lib.types.lines
          lib.types.path
        ]
      );
      default = { };
      description = ''
        Themes to be used with halloy. Each theme gets written to a themes directory accessible to halloy.
        See <https://halloy.chat/configuration/themes/index.html> for more information.
      '';
      example = lib.literalExpression ''
        {
          my-theme = {
            general = {
              background = "<string>";
              border = "<string>";
              horizontal_rule = "<string>";
              unread_indicator = "<string>";
            };
            text = {
              primary = "<string>";
              secondary = "<string>";
              tertiary = "<string>";
              success = "<string>";
              error = "<string>";
            };
          };
        }
      '';
    };
    generatedConfig.output = lib.mkOption {
      type = lib.types.str;
      default = config.outputName;
      description = ''
        The derivation output for the config generated by this wrapper module
      '';
    };
    generatedConfig.placeholder = lib.mkOption {
      type = lib.types.str;
      default = "${placeholder config.generatedConfig.output}/${config.binName}-config";
      readOnly = true;
      description = ''
        The placeholder accessible in the wrapper derivation build script for the config generated by this wrapper module
      '';
    };
  };

  config = {
    package = lib.mkDefault pkgs.halloy;
    env.XDG_CONFIG_HOME = lib.mkIf (config.settings != { }) config.generatedConfig.placeholder;
    passthru = lib.optionalAttrs (config.settings != { }) {
      generatedConfig = "${
        config.wrapper.${config.generatedConfig.output}
      }/${config.binName}-config/halloy";
    };
    buildCommand.makeThemesAnyway = ''
      mkdir -p "${config.generatedConfig.placeholder}/halloy/themes"
    '';
    constructFiles = {
      config = lib.mkIf (config.settings != { }) {
        content = builtins.toJSON config.settings;
        relPath = lib.mkOverride 0 "${config.binName}-config/halloy/config.toml";
        output = lib.mkOverride 0 config.generatedConfig.output;
        builder = ''mkdir -p "$(dirname "$2")" && ${pkgs.remarshal}/bin/json2toml "$1" "$2"'';
      };
    }
    // lib.pipe config.themes [
      (lib.filterAttrs (_: theme: theme != { } && theme != ""))
      (builtins.mapAttrs (
        name: theme: {
          relPath = lib.mkOverride 0 "${config.binName}-config/halloy/themes/${name}.toml";
          output = lib.mkOverride 0 config.generatedConfig.output;
          content =
            if builtins.isString theme then
              theme
            else if !(builtins.isPath theme || lib.isStorePath theme) then
              builtins.toJSON theme
            else
              "";
          builder =
            if builtins.isString theme then
              ''mkdir -p "$(dirname "$2")" && cp "$1" "$2"''
            else if builtins.isPath theme || lib.isStorePath theme then
              ''mkdir -p "$(dirname "$2")" && cp ${theme} "$2"''
            else
              ''mkdir -p "$(dirname "$2")" && ${pkgs.remarshal}/bin/json2toml "$1" "$2"'';
        }
      ))
    ];
    meta.maintainers = [ wlib.maintainers.ricardomaps ];

  };

}
