{
  config,
  lib,
  wlib,
  pkgs,
  ...
}:
{
  imports = [ wlib.modules.default ];
  options = {
    emacsPackages = lib.mkOption {
      type = wlib.types.withPackagesType;
      default = ps: [ ];
      example = lib.literalExpression "epkgs: with epkgs.melpaPackages; [ evil ivy ]";
      description = "Packages for emacs. This value is provided to pkgs.emacs.pkgs.withPackages, so it should
either be a list of emacs packages, or a function that takes a single input and returns a list of packages.
That input provides `.melpaPackages` which contains all packages from Melpa.";
    };
    configFile = lib.mkOption {
      type = lib.types.lines;
      default = "";
      example = ''
        (require 'use-package)

        (setq inhibit-startup-message t)
        (set-fringe-mode 10)
      '';
      description = ''
        emacs config file.

        Because of emacs quirks, if `~/.emacs` exists, then it will be used first.
        If you need to work around this, add `[ [ "-l" config.constructFiles.init.path ] "-q" ]`
        to `config.addFlag`, or set those arguments via `config.flags`.
      '';
    };
    earlyConfigFile = lib.mkOption {
      type = lib.types.lines;
      default = "";
      example = ''
        (setq extra-files-path $${./path/to/extra/files})
      '';
      description = "The contents of `early-init.el`.";
    };
    userDirectory = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = "~/.emacs.d";
      description = "After loading our config file, `user-emacs-directory` will be set to the value of this
option. If the option is null, `user-emacs-directory` will point to a read-only location in the nix store
(not recommended, since some emacs packages depend on being able to write to the user config directory).

This is done at the start of `early-init.el`.";
    };
    generatedConfigOutput = lib.mkOption {
      type = lib.types.str;
      default = config.outputName;
      description = ''
        The derivation output for the config generated by this wrapper module
      '';
    };
  };
  config.wrapperImplementation = "binary";
  config.passthru.generatedConfig = "${config.wrapper.${config.generatedConfigOutput}}/emacs.d";
  config.constructFiles.early-init = {
    key = "earlyInit";
    output = lib.mkOverride 0 config.generatedConfigOutput;
    relPath = lib.mkOverride 0 "emacs.d/early-init.el";
    content =
      lib.optionalString (config.userDirectory != null) ''
        (setq user-emacs-directory "${config.userDirectory}")
      ''
      + config.earlyConfigFile;
  };
  config.constructFiles.init = {
    relPath = lib.mkOverride 0 "emacs.d/init.el";
    output = lib.mkOverride 0 config.generatedConfigOutput;
    content = config.configFile;
  };
  config.wrapperVariants = {
    "emacs-${config.package.emacs.version}" = { };
  };
  config.flags."--init-directory" = lib.mkIf (
    config.configFile != "" || config.earlyConfigFile != ""
  ) "${dirOf config.constructFiles.init.path}";
  config.package = lib.mkDefault pkgs.emacs;
  config.overrides = [
    {
      name = "emacsPackages";
      data = v: v.pkgs.withPackages config.emacsPackages;
    }
  ];
  config.meta.description = "Wrapper for emacs";
  config.meta.maintainers = [ wlib.maintainers.boundless-recursion ];
}
