{
  config,
  lib,
  wlib,
  pkgs,
  ...
}:
let
  tomlFmt = pkgs.formats.toml { };
  hasConfig =
    config.settings != { }
    || config.extraSettings != ""
    || config.languages != { }
    || config.ignores != [ ]
    || config.themes != { };
in
{
  imports = [ wlib.modules.default ];
  options = {
    settings = lib.mkOption {
      type = tomlFmt.type;
      description = ''
        General settings
        See <https://docs.helix-editor.com/configuration.html> 
      '';
      default = { };
    };
    extraSettings = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = ''
        Extra lines appended to the config file.
      '';
    };
    languages = lib.mkOption {
      type = tomlFmt.type;
      description = ''
        Language specific settings
        See <https://docs.helix-editor.com/languages.html>
      '';
      default = { };
    };
    themes = lib.mkOption {
      type = lib.types.attrsOf (
        lib.types.oneOf [
          tomlFmt.type
          lib.types.lines
        ]
      );
      description = ''
        Themes to add to config.
        See <https://docs.helix-editor.com/themes.html>
      '';
      default = { };
    };
    ignores = lib.mkOption {
      type = lib.types.listOf lib.types.nonEmptyStr;
      default = [ ];
      description = ''
        List of paths to be ignored by the file-picker.
        The format is the same as in .gitignore.
      '';
    };
    generatedConfig.output = lib.mkOption {
      type = lib.types.str;
      default = config.outputName;
      description = ''
        The derivation output for the config generated by this wrapper module
      '';
    };
    generatedConfig.placeholder = lib.mkOption {
      type = lib.types.str;
      default = "${placeholder config.generatedConfig.output}/${config.binName}-config";
      readOnly = true;
      description = ''
        The placeholder accessible in the wrapper derivation build script for the config generated by this wrapper module
      '';
    };
  };
  config.package = lib.mkDefault pkgs.helix;
  config.env.XDG_CONFIG_HOME = lib.mkIf hasConfig config.generatedConfig.placeholder;
  config.passthru = lib.optionalAttrs hasConfig {
    generatedConfig = "${
      config.wrapper.${config.generatedConfig.output}
    }/${config.binName}-config/helix";
  };
  config.drv.extraSettings = config.extraSettings;
  config.drv.passAsFile = [ "extraSettings" ];
  config.constructFiles = {
    config = lib.mkIf (config.settings != { } || config.extraSettings != "") {
      relPath = lib.mkOverride 0 "${config.binName}-config/helix/config.toml";
      output = lib.mkOverride 0 config.generatedConfig.output;
      content = builtins.toJSON config.settings;
      builder = ''
        mkdir -p "$(dirname "$2")" && \
        ${pkgs.remarshal}/bin/json2toml "$1" "$2" && \
        cat "$extraSettingsPath" >> "$2"
      '';
    };
    languages = lib.mkIf (config.languages != { }) {
      relPath = lib.mkOverride 0 "${config.binName}-config/helix/languages.toml";
      output = lib.mkOverride 0 config.generatedConfig.output;
      content = builtins.toJSON config.languages;
      builder = ''mkdir -p "$(dirname "$2")" && ${pkgs.remarshal}/bin/json2toml "$1" "$2"'';
    };
    ignore = lib.mkIf (config.ignores != [ ]) {
      relPath = lib.mkOverride 0 "${config.binName}-config/helix/ignore";
      output = lib.mkOverride 0 config.generatedConfig.output;
      content = lib.strings.concatLines config.ignores;
    };
  }
  // lib.pipe config.themes [
    (lib.filterAttrs (_: theme: theme != { }))
    (builtins.mapAttrs (
      name: theme: {
        key = "theme_${name}";
        relPath = lib.mkOverride 0 "${config.binName}-config/helix/themes/${name}.toml";
        output = lib.mkOverride 0 config.generatedConfig.output;
        content = if builtins.isString theme then theme else builtins.toJSON theme;
        ${if builtins.isString theme then null else "builder"} =
          ''mkdir -p "$(dirname "$2")" && ${pkgs.remarshal}/bin/json2toml "$1" "$2"'';
      }
    ))
  ];
  config.meta.maintainers = [ wlib.maintainers.birdee ];
}
